<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [1]:
##### Your Code Here #####
import numpy as np
import pandas as pd

In [3]:
x = np.array(([0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [0, 1, 0],
              [1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]), dtype = float)

y = np.array(([0],
              [1],
              [1],
              [1],
              [1],
              [0],
              [0]), dtype = float)

In [12]:
class NeuralNetwork:
    
    def __init__(self, inputs, hidden, outputs):
        self.inputs = inputs
        self.hiddenNodes = hidden
        self.outputNodes = outputs
        
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def feed_forward(self, x):
        self.hidden_sum = np.dot(x, self.weights1)
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output

In [13]:
nn = NeuralNetwork(3, 4, 1)

In [14]:
# Weights
print("Layer 1 weights: \n", nn.weights1)
print("Layer 2 weights: \n", nn.weights2)

Layer 1 weights: 
 [[ 0.21202041 -1.16999699 -0.04736228  0.13626979]
 [ 1.62267684 -0.96843319  0.24433879 -1.01822338]
 [ 0.02853985  0.5206508  -0.52553694 -0.52494842]]
Layer 2 weights: 
 [[0.36688249]
 [0.49850977]
 [0.93558667]
 [0.37657029]]


In [17]:
# Output
output = nn.feed_forward(x[0])
print("intput", x[0])
print("output", output)
print("true_output", y[0])

intput [0. 0. 1.]
output [0.72837006]
true_output [0.]


In [18]:
# Error
error = y[0] - output
print(error)

[-0.72837006]


In [19]:
output_all = nn.feed_forward(x)
error_all = y - output_all

print(output_all)
print(error_all)
print(y)

[[0.72837006]
 [0.72530967]
 [0.70390173]
 [0.74425178]
 [0.72685055]
 [0.70387472]
 [0.7481509 ]]
[[-0.72837006]
 [ 0.27469033]
 [ 0.29609827]
 [ 0.25574822]
 [ 0.27314945]
 [-0.70387472]
 [-0.7481509 ]]
[[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]


## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [ ]:
##### Your Code Here #####

## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?